<a href="https://colab.research.google.com/github/oksanayefimova/AES_repo/blob/dev_icnale/Fairness_of_Scorring_System_ICNALE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fairness of Scorring System: ICNALE

In [4]:
from google.colab import drive
import os
import pandas as pd

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1. ICNALE Participant Background Survey Sheet

In [5]:
import pandas as pd
file_path = '/content/drive/MyDrive/AES_data/ICNALE_Survey_202603.xlsx'
xls = pd.ExcelFile(file_path)
print("Sheet names:", xls.sheet_names)
participants = pd.read_excel(file_path, sheet_name=xls.sheet_names[1])

Sheet names: ['Info Type', 'Participants']

In [7]:
participants.columns

Index(['Module', 'Code', 'Country', 'L1', 'PTJ1 (wds)', 'PTJ2 (wds)',
       'SMK1 (wds)', 'SMK2 (wds)', 'Self Evaluation', 'Sex', 'Age',
       'Grade/Degree', 'Months of Stay in English Speaking Area (< n months)',
       'ENS Type', 'Major/ Occupation', 'Academic Genre', 'Proficiency Test',
       'Score', 'Vocabulary Size Test Score', 'CEFR Level',
       'INTM (Integrative Motivation)', 'INSM (Instrumental Motivation)',
       'INTM+INSM', 'INTM-INSM',
       'Primary (Amount of Using Eng at Primary Schools)',
       'Secondary (Amount of Using Eng at Secondary Schools)',
       'College (Amount of Using Eng at Colleges)',
       'Inschool (Amount of Using Eng in Schools)',
       'Outschool (Amount of Using Eng outside Schools)',
       'Listening (Amount of Studying "Listening")',
       'Reading (Amount of Studying "Reading")',
       'Speaking (Amount of Studying "Speaking")',
       'Writing (Amount of Studying "Writing")',
       'NS (Amount of Learning from NS Teachers)',
       'Pronunciation (Amount of Learning Pronunciation)',
       'Presentation (Amount of Learning Eng Presentations)',
       'EssayW (Amount of Learning Essay Writing)',
       'Like to talk in L1 (Attitude)', 'Like to talk in L2 (Attitude)'],
      dtype='object')

In [ ]:
participants.Module.unique()

array(['SD', 'SM', 'WE', 'WEP'], dtype=object)

i think we need only Module = WE

## 2. Essays (from Written essays WE)

In [ ]:
WE_FOLDER_PATH = '/content/drive/MyDrive/AES_data/ICNALE_WE_2.6/WE_0_Unclassified_Unmerged'
data = []

# for each essay in the dir
for filename in os.listdir(WE_FOLDER_PATH):
    if filename.endswith(".txt"):
        name_without_ext = filename.replace('.txt', '')
        parts = name_without_ext.split('_')

        # read the file name structure
        if len(parts) >= 5:
            module = parts[0]    # WE
            region = parts[1]    # CHN
            task = parts[2]      # PTJ0
            student_id = parts[3] # 001
            cefr = "_".join(parts[4:]) # B1_1

            # read essay text
            file_path = os.path.join(WE_FOLDER_PATH, filename)
            with open(file_path, 'r', encoding='utf-8') as f:
                text = f.read().strip()

            data.append({
                'filename': name_without_ext,
                'region': region,
                'task': task,
                'student_id': student_id,
                'cefr_level': cefr,
                'essay_text': text
            })

df_essays = pd.DataFrame(data)
df_essays.head()

,filename,region,task,student_id,cefr_level,essay_text
0,WE_TWN_SMK0_035_B1_1,TWN,SMK0,035,B1_1,﻿About smoking should be completely banned at ...
1,WE_TWN_SMK0_048_B2_0,TWN,SMK0,048,B2_0,"﻿My answer is ""YES. "" Smoking should be comple..."
2,WE_TWN_SMK0_069_B2_0,TWN,SMK0,069,B2_0,﻿I disagree on the idea that smoking should be...
3,WE_TWN_SMK0_064_B1_1,TWN,SMK0,064,B1_1,﻿I think it will be pleasure for many people i...
4,WE_TWN_SMK0_066_B1_2,TWN,SMK0,066,B1_2,﻿Smoking has been generally viewed as a seriou...

In [ ]:
df_essays['filename'] = df_essays['filename'].str[3:]

In [ ]:
df_essays

,filename,region,task,student_id,cefr_level,essay_text
0,TWN_SMK0_035_B1_1,TWN,SMK0,035,B1_1,﻿About smoking should be completely banned at ...
1,TWN_SMK0_048_B2_0,TWN,SMK0,048,B2_0,"﻿My answer is ""YES. "" Smoking should be comple..."
2,TWN_SMK0_069_B2_0,TWN,SMK0,069,B2_0,﻿I disagree on the idea that smoking should be...
3,TWN_SMK0_064_B1_1,TWN,SMK0,064,B1_1,﻿I think it will be pleasure for many people i...
4,TWN_SMK0_066_B1_2,TWN,SMK0,066,B1_2,﻿Smoking has been generally viewed as a seriou...
...,...,...,...,...,...,...
5595,CHN_SMK0_068_B1_1,CHN,SMK0,068,B1_1,﻿I don't suppose that it's a wise idea to ban ...
5596,CHN_SMK0_074_B1_2,CHN,SMK0,074,B1_2,"﻿As is known to all, cigarette is popular for ..."
5597,CHN_SMK0_062_B1_1,CHN,SMK0,062,B1_1,﻿I think that smoking should be completely ban...
5598,CHN_SMK0_061_A2_0,CHN,SMK0,061,A2_0,﻿Today cigarettes exist everywhere. People can...
5599,CHN_SMK0_054_B1_1,CHN,SMK0,054,B1_1,﻿We can see people with a cigarette at every c...

## Scores (From Edited Essays EE)

In [ ]:
import pandas as pd
file_path = '/content/drive/MyDrive/AES_data/ICNALE_EE_3.1/ICNALE_EE_3.1/ICNALE EE Infosheet.xlsx'
xls = pd.ExcelFile(file_path)
print("Sheet names:", xls.sheet_names)

Sheet names: ['Sheet1']

In [ ]:
# columns_to_keep = [
#     'WEriter Code',
#     'Content (/12)',
#     'Organization (/12)',
#     'Vocabulary (/12)',
#     'Language Use (/12)',
#     'Mechanics (/12)',
#     'Total 1 (%)',
#     'Total 2 (Weighted %)'
# ]

scores = pd.read_excel(file_path, sheet_name=xls.sheet_names[0], header=1)
scores = scores.rename(columns={'WEriter Code': 'student_id'})
scores

,student_id,Sex,Age,Grade/Degree,Yrs of Stay (< Yrs),Major,Acad. Genre,Prof. Test,Score,Vocab Size Test,...,Total 2 (Weighted %),File Name,Country,Topic,Learners' Prof.,Editor,Tokens.1,A (Added),D (Deleted),A+D
0,WE_CHN_001,F,20,2.0,NaN,Law,Social Sciences,CEE,72,30,...,68.3,EE_CHN_PTJ0_001_B1_1_EDIT,CHN,PTJ,B1_1,LC,275,34,29,63
1,WE_CHN_002,F,21,3.0,NaN,Law,Social Sciences,CEE,77,27,...,62.1,EE_CHN_PTJ0_002_B1_1_EDIT,CHN,PTJ,B1_1,LC,210,18,13,31
2,WE_CHN_003,F,20,3.0,NaN,Law,Social Sciences,CEE,79,32,...,73.8,EE_CHN_PTJ0_003_B1_1_EDIT,CHN,PTJ,B1_1,LC,255,29,17,46
3,WE_CHN_004,F,20,2.0,NaN,Chemistry,Sciences & Technology,CEE,87,37,...,62.1,EE_CHN_PTJ0_004_B1_2_EDIT,CHN,PTJ,B1_2,LC,267,27,25,52
4,WE_CHN_005,M,20,2.0,NaN,Chemistry,Sciences & Technology,CEE,84,44,...,70.8,EE_CHN_PTJ0_005_B1_2_EDIT,CHN,PTJ,B1_2,LC,228,27,26,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,WE_PHL_085,F,17,2.0,NaN,Finance,Social Sciences,NaN,NaN,34,...,59.6,EE_PHL_SMK0_085_B1_1_EDIT,PHL,SMK,B1_1,HAC,195,45,34,79
636,WE_PHL_113,F,18,3.0,NaN,Preschool Education,Humanities,NaN,NaN,28,...,32.5,EE_PHL_SMK0_113_B1_1_EDIT,PHL,SMK,B1_1,HAC,194,41,40,81
637,WE_PHL_114,M,19,1.0,NaN,Finance,Social Sciences,NaN,NaN,32,...,69.6,EE_PHL_SMK0_114_B1_1_EDIT,PHL,SMK,B1_1,HAC,221,52,40,92
638,WE_PHL_123,F,18,2.0,NaN,English,Humanities,NaN,NaN,34,...,56.7,EE_PHL_SMK0_123_B1_1_EDIT,PHL,SMK,B1_1,HAC,218,62,53,115
639,WE_PHL_148,F,17,NaN,NaN,Finance,Social Sciences,NaN,NaN,33,...,88.3,EE_PHL_SMK0_148_B1_1_EDIT,PHL,SMK,B1_1,HAC,205,36,27,63

In [ ]:
scores['File Name'] = scores['File Name'].str[3:-5]
scores.columns

NameError: name 'scores' is not defined

In [ ]:
scores.merge(right=df_essays, left_on='File Name', right_on='filename', how='inner')

,student_id_x,Sex,Age,Grade/Degree,Yrs of Stay (< Yrs),Major,Acad. Genre,Prof. Test,Score,Vocab Size Test,...,Tokens.1,A (Added),D (Deleted),A+D,filename,region,task,student_id_y,cefr_level,essay_text
0,WE_CHN_001,F,20,2.0,NaN,Law,Social Sciences,CEE,72,30,...,275,34,29,63,CHN_PTJ0_001_B1_1,CHN,PTJ0,001,B1_1,﻿Now many parents and teachers disagree that c...
1,WE_CHN_002,F,21,3.0,NaN,Law,Social Sciences,CEE,77,27,...,210,18,13,31,CHN_PTJ0_002_B1_1,CHN,PTJ0,002,B1_1,"﻿In my opinion, I am strongly agree with the i..."
2,WE_CHN_003,F,20,3.0,NaN,Law,Social Sciences,CEE,79,32,...,255,29,17,46,CHN_PTJ0_003_B1_1,CHN,PTJ0,003,B1_1,"﻿As we all know, some college students have pa..."
3,WE_CHN_004,F,20,2.0,NaN,Chemistry,Sciences & Technology,CEE,87,37,...,267,27,25,52,CHN_PTJ0_004_B1_2,CHN,PTJ0,004,B1_2,﻿Society has more and more challenges for coll...
4,WE_CHN_005,M,20,2.0,NaN,Chemistry,Sciences & Technology,CEE,84,44,...,228,27,26,53,CHN_PTJ0_005_B1_2,CHN,PTJ0,005,B1_2,"﻿Nowadays, college education has attracted the..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,WE_PHL_085,F,17,2.0,NaN,Finance,Social Sciences,NaN,NaN,34,...,195,45,34,79,PHL_SMK0_085_B1_1,PHL,SMK0,085,B1_1,﻿Yes it should be because restaurant is an est...
556,WE_PHL_113,F,18,3.0,NaN,Preschool Education,Humanities,NaN,NaN,28,...,194,41,40,81,PHL_SMK0_113_B1_1,PHL,SMK0,113,B1_1,"﻿Yes, the smoking should be completely banned ..."
557,WE_PHL_114,M,19,1.0,NaN,Finance,Social Sciences,NaN,NaN,32,...,221,52,40,92,PHL_SMK0_114_B1_1,PHL,SMK0,114,B1_1,﻿Smoking should be banned in all restaurants i...
558,WE_PHL_123,F,18,2.0,NaN,English,Humanities,NaN,NaN,34,...,218,62,53,115,PHL_SMK0_123_B1_1,PHL,SMK0,123,B1_1,﻿Cigarette Smoking is dangerous to your health...
559,WE_PHL_148,F,17,NaN,NaN,Finance,Social Sciences,NaN,NaN,33,...,205,36,27,63,PHL_SMK0_148_B1_1,PHL,SMK0,148,B1_1,﻿Smoking should be banned in all restaurants b...